<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        Country::truncate();

        Country::insert([
            ['country' => 'Afghanistan', 'nationality' => 'Afghane', 'alpha' => 'af', 'code' => '93', 'embassy' => 0],
            ['country' => 'Afrique du Sud', 'nationality' => 'Sud-Africaine', 'alpha' => 'za', 'code' => '27', 'embassy' => 0],
            ['country' => 'Albanie', 'nationality' => 'Albanaise', 'alpha' => 'al', 'code' => '355', 'embassy' => 0],
            ['country' => 'Algérie', 'nationality' => 'Algérienne', 'alpha' => 'dz', 'code' => '213', 'embassy' => 0],
            ['country' => 'Allemagne', 'nationality' => 'Allemande', 'alpha' => 'de', 'code' => '49', 'embassy' => 0],
            ['country' => 'Andorre', 'nationality' => 'Andorrane', 'alpha' => 'ad', 'code' => '376', 'embassy' => 0],
            ['country' => 'Angola', 'nationality' => 'Angolaise', 'alpha' => 'ao', 'code' => '244', 'embassy' => 0],
            ['country' => 'Arabie saoudite', 'nationality' => 'Saoudienne', 'alpha' => 'sa', 'code' => '966', 'embassy' => 0],
            ['country' => 'Argentine', 'nationality' => 'Argentine', 'alpha' => 'ar', 'code' => '54', 'embassy' => 0],
            ['country' => 'Arménie', 'nationality' => 'Arménienne', 'alpha' => 'am', 'code' => '374', 'embassy' => 0],
            ['country' => 'Australie', 'nationality' => 'Australienne', 'alpha' => 'au', 'code' => '61', 'embassy' => 0],
            ['country' => 'Autriche', 'nationality' => 'Autrichienne', 'alpha' => 'at', 'code' => '43', 'embassy' => 0],
            ['country' => 'Azerbaïdjan', 'nationality' => 'Azerbaïdjanaise', 'alpha' => 'az', 'code' => '994', 'embassy' => 0],
            ['country' => 'Bahreïn', 'nationality' => 'Bahreïnie', 'alpha' => 'bh', 'code' => '973', 'embassy' => 0],
            ['country' => 'Bangladesh', 'nationality' => 'Bangladeshie', 'alpha' => 'bd', 'code' => '880', 'embassy' => 0],
            ['country' => 'Belgique', 'nationality' => 'Belge', 'alpha' => 'be', 'code' => '32', 'embassy' => 0],
            ['country' => 'Bénin', 'nationality' => 'Béninoise', 'alpha' => 'bj', 'code' => '229', 'embassy' => 0],
            ['country' => 'Bhoutan', 'nationality' => 'Bhoutanaise', 'alpha' => 'bt', 'code' => '975', 'embassy' => 0],
            ['country' => 'Biélorussie', 'nationality' => 'Biélorusse', 'alpha' => 'by', 'code' => '375', 'embassy' => 0],
            ['country' => 'Bolivie', 'nationality' => 'Bolivienne', 'alpha' => 'bo', 'code' => '591', 'embassy' => 0],
            ['country' => 'Bosnie-Herzégovine', 'nationality' => 'Bosnienne', 'alpha' => 'ba', 'code' => '387', 'embassy' => 0],
            ['country' => 'Botswana', 'nationality' => 'Botswanaise', 'alpha' => 'bw', 'code' => '267', 'embassy' => 0],
            ['country' => 'Brésil', 'nationality' => 'Brésilienne', 'alpha' => 'br', 'code' => '55', 'embassy' => 0],
            ['country' => 'Bulgarie', 'nationality' => 'Bulgare', 'alpha' => 'bg', 'code' => '359', 'embassy' => 0],
            ['country' => 'Burkina Faso', 'nationality' => 'Burkinabè', 'alpha' => 'bf', 'code' => '226', 'embassy' => 0],
            ['country' => 'Burundi', 'nationality' => 'Burundaise', 'alpha' => 'bi', 'code' => '257', 'embassy' => 0],
            ['country' => 'Cambodge', 'nationality' => 'Cambodgienne', 'alpha' => 'kh', 'code' => '855', 'embassy' => 0],
            ['country' => 'Cameroun', 'nationality' => 'Camerounaise', 'alpha' => 'cm', 'code' => '237', 'embassy' => 0],
            ['country' => 'Canada', 'nationality' => 'Canadienne', 'alpha' => 'ca', 'code' => '1', 'embassy' => 0],
            ['country' => 'Cap-Vert', 'nationality' => 'Cap-Verdienne', 'alpha' => 'cv', 'code' => '238', 'embassy' => 0],
            ['country' => 'Chili', 'nationality' => 'Chilienne', 'alpha' => 'cl', 'code' => '56', 'embassy' => 0],
            ['country' => 'Chine', 'nationality' => 'Chinoise', 'alpha' => 'cn', 'code' => '86', 'embassy' => 0],
            ['country' => 'Chypre', 'nationality' => 'Chypriote', 'alpha' => 'cy', 'code' => '357', 'embassy' => 0],
            ['country' => 'Colombie', 'nationality' => 'Colombienne', 'alpha' => 'co', 'code' => '57', 'embassy' => 0],
            ['country' => 'Comores', 'nationality' => 'Comorienne', 'alpha' => 'km', 'code' => '269', 'embassy' => 0],
            ['country' => 'Congo (Brazzaville)', 'nationality' => 'Congolaise', 'alpha' => 'cg', 'code' => '242', 'embassy' => 0],
            ['country' => 'Congo (Kinshasa)', 'nationality' => 'Congolaise (RDC)', 'alpha' => 'cd', 'code' => '243', 'embassy' => 0],
            ['country' => 'Corée du Nord', 'nationality' => 'Nord-Coréenne', 'alpha' => 'kp', 'code' => '850', 'embassy' => 0],
            ['country' => 'Corée du Sud', 'nationality' => 'Sud-Coréenne', 'alpha' => 'kr', 'code' => '82', 'embassy' => 0],
            ['country' => 'Costa Rica', 'nationality' => 'Costaricienne', 'alpha' => 'cr', 'code' => '506', 'embassy' => 0],
            ['country' => 'Côte d’Ivoire', 'nationality' => 'Ivoirienne', 'alpha' => 'ci', 'code' => '225', 'embassy' => 1],
            ['country' => 'Croatie', 'nationality' => 'Croate', 'alpha' => 'hr', 'code' => '385', 'embassy' => 0],
            ['country' => 'Cuba', 'nationality' => 'Cubaine', 'alpha' => 'cu', 'code' => '53', 'embassy' => 0],
            ['country' => 'Danemark', 'nationality' => 'Danoise', 'alpha' => 'dk', 'code' => '45', 'embassy' => 0],
            ['country' => 'Djibouti', 'nationality' => 'Djiboutienne', 'alpha' => 'dj', 'code' => '253', 'embassy' => 0],
            ['country' => 'Égypte', 'nationality' => 'Égyptienne', 'alpha' => 'eg', 'code' => '20', 'embassy' => 0],
            ['country' => 'Émirats arabes unis', 'nationality' => 'Émiratie', 'alpha' => 'ae', 'code' => '971', 'embassy' => 0],
            ['country' => 'Équateur', 'nationality' => 'Équatorienne', 'alpha' => 'ec', 'code' => '593', 'embassy' => 0],
            ['country' => 'Érythrée', 'nationality' => 'Érythréenne', 'alpha' => 'er', 'code' => '291', 'embassy' => 0],
            ['country' => 'Espagne', 'nationality' => 'Espagnole', 'alpha' => 'es', 'code' => '34', 'embassy' => 0],
            ['country' => 'Estonie', 'nationality' => 'Estonienne', 'alpha' => 'ee', 'code' => '372', 'embassy' => 0],
            ['country' => 'États-Unis', 'nationality' => 'Américaine', 'alpha' => 'us', 'code' => '1', 'embassy' => 0],
            ['country' => 'Éthiopie', 'nationality' => 'Éthiopienne', 'alpha' => 'et', 'code' => '251', 'embassy' => 0],
            ['country' => 'Finlande', 'nationality' => 'Finlandaise', 'alpha' => 'fi', 'code' => '358', 'embassy' => 0],
            ['country' => 'France', 'nationality' => 'Française', 'alpha' => 'fr', 'code' => '33', 'embassy' => 0],
            ['country' => 'Gabon', 'nationality' => 'Gabonaise', 'alpha' => 'ga', 'code' => '241', 'embassy' => 0],
            ['country' => 'Gambie', 'nationality' => 'Gambienne', 'alpha' => 'gm', 'code' => '220', 'embassy' => 0],
            ['country' => 'Géorgie', 'nationality' => 'Géorgienne', 'alpha' => 'ge', 'code' => '995', 'embassy' => 0],
            ['country' => 'Ghana', 'nationality' => 'Ghanéenne', 'alpha' => 'gh', 'code' => '233', 'embassy' => 0],
            ['country' => 'Grèce', 'nationality' => 'Grecque', 'alpha' => 'gr', 'code' => '30', 'embassy' => 0],
            ['country' => 'Guinée', 'nationality' => 'Guinéenne', 'alpha' => 'gn', 'code' => '224', 'embassy' => 0],
            ['country' => 'Haïti', 'nationality' => 'Haïtienne', 'alpha' => 'ht', 'code' => '509', 'embassy' => 0],
            ['country' => 'Honduras', 'nationality' => 'Hondurienne', 'alpha' => 'hn', 'code' => '504', 'embassy' => 0],
            ['country' => 'Hongrie', 'nationality' => 'Hongroise', 'alpha' => 'hu', 'code' => '36', 'embassy' => 0],
            ['country' => 'Inde', 'nationality' => 'Indienne', 'alpha' => 'in', 'code' => '91', 'embassy' => 0],
            ['country' => 'Indonésie', 'nationality' => 'Indonésienne', 'alpha' => 'id', 'code' => '62', 'embassy' => 0],
            ['country' => 'Irak', 'nationality' => 'Irakienne', 'alpha' => 'iq', 'code' => '964', 'embassy' => 0],
            ['country' => 'Iran', 'nationality' => 'Iranienne', 'alpha' => 'ir', 'code' => '98', 'embassy' => 0],
            ['country' => 'Irlande', 'nationality' => 'Irlandaise', 'alpha' => 'ie', 'code' => '353', 'embassy' => 0],
            ['country' => 'Islande', 'nationality' => 'Islandaise', 'alpha' => 'is', 'code' => '354', 'embassy' => 0],
            ['country' => 'Israël', 'nationality' => 'Israélienne', 'alpha' => 'il', 'code' => '972', 'embassy' => 0],
            ['country' => 'Italie', 'nationality' => 'Italienne', 'alpha' => 'it', 'code' => '39', 'embassy' => 0],
            ['country' => 'Japon', 'nationality' => 'Japonaise', 'alpha' => 'jp', 'code' => '81', 'embassy' => 0],
            ['country' => 'Jordanie', 'nationality' => 'Jordanienne', 'alpha' => 'jo', 'code' => '962', 'embassy' => 0],
            ['country' => 'Kenya', 'nationality' => 'Kényane', 'alpha' => 'ke', 'code' => '254', 'embassy' => 0],
            ['country' => 'Koweït', 'nationality' => 'Koweïtienne', 'alpha' => 'kw', 'code' => '965', 'embassy' => 0],
            ['country' => 'Laos', 'nationality' => 'Laotienne', 'alpha' => 'la', 'code' => '856', 'embassy' => 0],
            ['country' => 'Lettonie', 'nationality' => 'Lettone', 'alpha' => 'lv', 'code' => '371', 'embassy' => 0],
            ['country' => 'Liban', 'nationality' => 'Libanaise', 'alpha' => 'lb', 'code' => '961', 'embassy' => 0],
            ['country' => 'Libye', 'nationality' => 'Libyenne', 'alpha' => 'ly', 'code' => '218', 'embassy' => 0],
            ['country' => 'Lituanie', 'nationality' => 'Lituanienne', 'alpha' => 'lt', 'code' => '370', 'embassy' => 0],
            ['country' => 'Luxembourg', 'nationality' => 'Luxembourgeoise', 'alpha' => 'lu', 'code' => '352', 'embassy' => 0],
            ['country' => 'Madagascar', 'nationality' => 'Malgache', 'alpha' => 'mg', 'code' => '261', 'embassy' => 0],
            ['country' => 'Malaisie', 'nationality' => 'Malaisienne', 'alpha' => 'my', 'code' => '60', 'embassy' => 0],
            ['country' => 'Mali', 'nationality' => 'Malienne', 'alpha' => 'ml', 'code' => '223', 'embassy' => 0],
            ['country' => 'Maroc', 'nationality' => 'Marocaine', 'alpha' => 'ma', 'code' => '212', 'embassy' => 0],
            ['country' => 'Mexique', 'nationality' => 'Mexicaine', 'alpha' => 'mx', 'code' => '52', 'embassy' => 0],
            ['country' => 'Monaco', 'nationality' => 'Monégasque', 'alpha' => 'mc', 'code' => '377', 'embassy' => 0],
            ['country' => 'Mongolie', 'nationality' => 'Mongole', 'alpha' => 'mn', 'code' => '976', 'embassy' => 0],
            ['country' => 'Mozambique', 'nationality' => 'Mozambicaine', 'alpha' => 'mz', 'code' => '258', 'embassy' => 0],
            ['country' => 'Namibie', 'nationality' => 'Namibienne', 'alpha' => 'na', 'code' => '264', 'embassy' => 0],
            ['country' => 'Népal', 'nationality' => 'Népalaise', 'alpha' => 'np', 'code' => '977', 'embassy' => 0],
            ['country' => 'Niger', 'nationality' => 'Nigérienne', 'alpha' => 'ne', 'code' => '227', 'embassy' => 0],
            ['country' => 'Nigeria', 'nationality' => 'Nigériane', 'alpha' => 'ng', 'code' => '234', 'embassy' => 0],
            ['country' => 'Norvège', 'nationality' => 'Norvégienne', 'alpha' => 'no', 'code' => '47', 'embassy' => 0],
            ['country' => 'Nouvelle-Zélande', 'nationality' => 'Néo-Zélandaise', 'alpha' => 'nz', 'code' => '64', 'embassy' => 0],
            ['country' => 'Ouganda', 'nationality' => 'Ougandaise', 'alpha' => 'ug', 'code' => '256', 'embassy' => 0],
            ['country' => 'Ouzbékistan', 'nationality' => 'Ouzbèke', 'alpha' => 'uz', 'code' => '998', 'embassy' => 0],
            ['country' => 'Pakistan', 'nationality' => 'Pakistanaise', 'alpha' => 'pk', 'code' => '92', 'embassy' => 0],
            ['country' => 'Panama', 'nationality' => 'Panaméenne', 'alpha' => 'pa', 'code' => '507', 'embassy' => 0],
            ['country' => 'Paraguay', 'nationality' => 'Paraguayenne', 'alpha' => 'py', 'code' => '595', 'embassy' => 0],
            ['country' => 'Pays-Bas', 'nationality' => 'Néerlandaise', 'alpha' => 'nl', 'code' => '31', 'embassy' => 0],
            ['country' => 'Pérou', 'nationality' => 'Péruvienne', 'alpha' => 'pe', 'code' => '51', 'embassy' => 0],
            ['country' => 'Philippines', 'nationality' => 'Philippine', 'alpha' => 'ph', 'code' => '63', 'embassy' => 0],
            ['country' => 'Pologne', 'nationality' => 'Polonaise', 'alpha' => 'pl', 'code' => '48', 'embassy' => 0],
            ['country' => 'Portugal', 'nationality' => 'Portugaise', 'alpha' => 'pt', 'code' => '351', 'embassy' => 0],
            ['country' => 'Qatar', 'nationality' => 'Qatarie', 'alpha' => 'qa', 'code' => '974', 'embassy' => 0],
            ['country' => 'République centrafricaine', 'nationality' => 'Centrafricaine', 'alpha' => 'cf', 'code' => '236', 'embassy' => 0],
            ['country' => 'République dominicaine', 'nationality' => 'Dominicaine', 'alpha' => 'do', 'code' => '1', 'embassy' => 0],
            ['country' => 'Roumanie', 'nationality' => 'Roumaine', 'alpha' => 'ro', 'code' => '40', 'embassy' => 0],
            ['country' => 'Royaume-Uni', 'nationality' => 'Britannique', 'alpha' => 'gb', 'code' => '44', 'embassy' => 0],
            ['country' => 'Russie', 'nationality' => 'Russe', 'alpha' => 'ru', 'code' => '7', 'embassy' => 0],
            ['country' => 'Rwanda', 'nationality' => 'Rwandaise', 'alpha' => 'rw', 'code' => '250', 'embassy' => 0],
            ['country' => 'Sénégal', 'nationality' => 'Sénégalaise', 'alpha' => 'sn', 'code' => '221', 'embassy' => 0],
            ['country' => 'Serbie', 'nationality' => 'Serbe', 'alpha' => 'rs', 'code' => '381', 'embassy' => 0],
            ['country' => 'Sierra Leone', 'nationality' => 'Sierra-Léonaise', 'alpha' => 'sl', 'code' => '232', 'embassy' => 0],
            ['country' => 'Singapour', 'nationality' => 'Singapourienne', 'alpha' => 'sg', 'code' => '65', 'embassy' => 0],
            ['country' => 'Slovaquie', 'nationality' => 'Slovaque', 'alpha' => 'sk', 'code' => '421', 'embassy' => 0],
            ['country' => 'Slovénie', 'nationality' => 'Slovène', 'alpha' => 'si', 'code' => '386', 'embassy' => 0],
            ['country' => 'Somalie', 'nationality' => 'Somalienne', 'alpha' => 'so', 'code' => '252', 'embassy' => 0],
            ['country' => 'Soudan', 'nationality' => 'Soudanaise', 'alpha' => 'sd', 'code' => '249', 'embassy' => 0],
            ['country' => 'Soudan du Sud', 'nationality' => 'Sud-Soudanaise', 'alpha' => 'ss', 'code' => '211', 'embassy' => 0],
            ['country' => 'Sri Lanka', 'nationality' => 'Sri Lankaise', 'alpha' => 'lk', 'code' => '94', 'embassy' => 0],
            ['country' => 'Suède', 'nationality' => 'Suédoise', 'alpha' => 'se', 'code' => '46', 'embassy' => 0],
            ['country' => 'Suisse', 'nationality' => 'Suisse', 'alpha' => 'ch', 'code' => '41', 'embassy' => 0],
            ['country' => 'Syrie', 'nationality' => 'Syrienne', 'alpha' => 'sy', 'code' => '963', 'embassy' => 0],
            ['country' => 'Tanzanie', 'nationality' => 'Tanzanienne', 'alpha' => 'tz', 'code' => '255', 'embassy' => 0],
            ['country' => 'Tchad', 'nationality' => 'Tchadienne', 'alpha' => 'td', 'code' => '235', 'embassy' => 0],
            ['country' => 'Thaïlande', 'nationality' => 'Thaïlandaise', 'alpha' => 'th', 'code' => '66', 'embassy' => 0],
            ['country' => 'Tunisie', 'nationality' => 'Tunisienne', 'alpha' => 'tn', 'code' => '216', 'embassy' => 0],
            ['country' => 'Turquie', 'nationality' => 'Turque', 'alpha' => 'tr', 'code' => '90', 'embassy' => 0],
            ['country' => 'Ukraine', 'nationality' => 'Ukrainienne', 'alpha' => 'ua', 'code' => '380', 'embassy' => 0],
            ['country' => 'Uruguay', 'nationality' => 'Uruguayenne', 'alpha' => 'uy', 'code' => '598', 'embassy' => 0],
            ['country' => 'Venezuela', 'nationality' => 'Vénézuélienne', 'alpha' => 've', 'code' => '58', 'embassy' => 0],
            ['country' => 'Viêt Nam', 'nationality' => 'Vietnamienne', 'alpha' => 'vn', 'code' => '84', 'embassy' => 0],
            ['country' => 'Yémen', 'nationality' => 'Yéménite', 'alpha' => 'ye', 'code' => '967', 'embassy' => 0],
            ['country' => 'Zambie', 'nationality' => 'Zambienne', 'alpha' => 'zm', 'code' => '260', 'embassy' => 0],
            ['country' => 'Zimbabwe', 'nationality' => 'Zimbabwéenne', 'alpha' => 'zw', 'code' => '263', 'embassy' => 0],
        ]);
    }
};