<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        Country::truncate();

        Country::insert([
            ['libelle'=>'Afghanistan','alpha'=>'af','code'=>'93','embassy'=>'0'],
            ['libelle'=>'Afrique du Sud','alpha'=>'za','code'=>'27','embassy'=>'0'],
            ['libelle'=>'Albanie','alpha'=>'al','code'=>'355','embassy'=>'0'],
            ['libelle'=>'Algérie','alpha'=>'dz','code'=>'213','embassy'=>'0'],
            ['libelle'=>'Allemagne','alpha'=>'de','code'=>'49','embassy'=>'0'],
            ['libelle'=>'Andorre','alpha'=>'ad','code'=>'376','embassy'=>'0'],
            ['libelle'=>'Angola','alpha'=>'ao','code'=>'244','embassy'=>'0'],
            ['libelle'=>'Arabie saoudite','alpha'=>'sa','code'=>'966','embassy'=>'0'],
            ['libelle'=>'Argentine','alpha'=>'ar','code'=>'54','embassy'=>'0'],
            ['libelle'=>'Arménie','alpha'=>'am','code'=>'374','embassy'=>'0'],
            ['libelle'=>'Australie','alpha'=>'au','code'=>'61','embassy'=>'0'],
            ['libelle'=>'Autriche','alpha'=>'at','code'=>'43','embassy'=>'0'],
            ['libelle'=>'Azerbaïdjan','alpha'=>'az','code'=>'994','embassy'=>'0'],
            ['libelle'=>'Bahreïn','alpha'=>'bh','code'=>'973','embassy'=>'0'],
            ['libelle'=>'Bangladesh','alpha'=>'bd','code'=>'880','embassy'=>'0'],
            ['libelle'=>'Belgique','alpha'=>'be','code'=>'32','embassy'=>'0'],
            ['libelle'=>'Bénin','alpha'=>'bj','code'=>'229','embassy'=>'0'],
            ['libelle'=>'Bhoutan','alpha'=>'bt','code'=>'975','embassy'=>'0'],
            ['libelle'=>'Biélorussie','alpha'=>'by','code'=>'375','embassy'=>'0'],
            ['libelle'=>'Bolivie','alpha'=>'bo','code'=>'591','embassy'=>'0'],
            ['libelle'=>'Bosnie-Herzégovine','alpha'=>'ba','code'=>'387','embassy'=>'0'],
            ['libelle'=>'Botswana','alpha'=>'bw','code'=>'267','embassy'=>'0'],
            ['libelle'=>'Brésil','alpha'=>'br','code'=>'55','embassy'=>'0'],
            ['libelle'=>'Bulgarie','alpha'=>'bg','code'=>'359','embassy'=>'0'],
            ['libelle'=>'Burkina Faso','alpha'=>'bf','code'=>'226','embassy'=>'0'],
            ['libelle'=>'Burundi','alpha'=>'bi','code'=>'257','embassy'=>'0'],
            ['libelle'=>'Cambodge','alpha'=>'kh','code'=>'855','embassy'=>'0'],
            ['libelle'=>'Cameroun','alpha'=>'cm','code'=>'237','embassy'=>'0'],
            ['libelle'=>'Canada','alpha'=>'ca','code'=>'1','embassy'=>'0'],
            ['libelle'=>'Cap-Vert','alpha'=>'cv','code'=>'238','embassy'=>'0'],
            ['libelle'=>'Chili','alpha'=>'cl','code'=>'56','embassy'=>'0'],
            ['libelle'=>'Chine','alpha'=>'cn','code'=>'86','embassy'=>'0'],
            ['libelle'=>'Chypre','alpha'=>'cy','code'=>'357','embassy'=>'0'],
            ['libelle'=>'Colombie','alpha'=>'co','code'=>'57','embassy'=>'0'],
            ['libelle'=>'Comores','alpha'=>'km','code'=>'269','embassy'=>'0'],
            ['libelle'=>'Congo (Brazzaville)','alpha'=>'cg','code'=>'242','embassy'=>'0'],
            ['libelle'=>'Congo (Kinshasa)','alpha'=>'cd','code'=>'243','embassy'=>'0'],
            ['libelle'=>'Corée du Nord','alpha'=>'kp','code'=>'850','embassy'=>'0'],
            ['libelle'=>'Corée du Sud','alpha'=>'kr','code'=>'82','embassy'=>'0'],
            ['libelle'=>'Costa Rica','alpha'=>'cr','code'=>'506','embassy'=>'0'],
            ['libelle'=>'Côte d’Ivoire','alpha'=>'ci','code'=>'225','embassy'=>'1'],
            ['libelle'=>'Croatie','alpha'=>'hr','code'=>'385','embassy'=>'0'],
            ['libelle'=>'Cuba','alpha'=>'cu','code'=>'53','embassy'=>'0'],
            ['libelle'=>'Danemark','alpha'=>'dk','code'=>'45','embassy'=>'0'],
            ['libelle'=>'Djibouti','alpha'=>'dj','code'=>'253','embassy'=>'0'],
            ['libelle'=>'Égypte','alpha'=>'eg','code'=>'20','embassy'=>'0'],
            ['libelle'=>'Émirats arabes unis','alpha'=>'ae','code'=>'971','embassy'=>'0'],
            ['libelle'=>'Équateur','alpha'=>'ec','code'=>'593','embassy'=>'0'],
            ['libelle'=>'Érythrée','alpha'=>'er','code'=>'291','embassy'=>'0'],
            ['libelle'=>'Espagne','alpha'=>'es','code'=>'34','embassy'=>'0'],
            ['libelle'=>'Estonie','alpha'=>'ee','code'=>'372','embassy'=>'0'],
            ['libelle'=>'États-Unis','alpha'=>'us','code'=>'1','embassy'=>'0'],
            ['libelle'=>'Éthiopie','alpha'=>'et','code'=>'251','embassy'=>'0'],
            ['libelle'=>'Finlande','alpha'=>'fi','code'=>'358','embassy'=>'0'],
            ['libelle'=>'France','alpha'=>'fr','code'=>'33','embassy'=>'0'],
            ['libelle'=>'Gabon','alpha'=>'ga','code'=>'241','embassy'=>'0'],
            ['libelle'=>'Gambie','alpha'=>'gm','code'=>'220','embassy'=>'0'],
            ['libelle'=>'Géorgie','alpha'=>'ge','code'=>'995','embassy'=>'0'],
            ['libelle'=>'Ghana','alpha'=>'gh','code'=>'233','embassy'=>'0'],
            ['libelle'=>'Grèce','alpha'=>'gr','code'=>'30','embassy'=>'0'],
            ['libelle'=>'Guinée','alpha'=>'gn','code'=>'224','embassy'=>'0'],
            ['libelle'=>'Haïti','alpha'=>'ht','code'=>'509','embassy'=>'0'],
            ['libelle'=>'Honduras','alpha'=>'hn','code'=>'504','embassy'=>'0'],
            ['libelle'=>'Hongrie','alpha'=>'hu','code'=>'36','embassy'=>'0'],
            ['libelle'=>'Inde','alpha'=>'in','code'=>'91','embassy'=>'0'],
            ['libelle'=>'Indonésie','alpha'=>'id','code'=>'62','embassy'=>'0'],
            ['libelle'=>'Irak','alpha'=>'iq','code'=>'964','embassy'=>'0'],
            ['libelle'=>'Iran','alpha'=>'ir','code'=>'98','embassy'=>'0'],
            ['libelle'=>'Irlande','alpha'=>'ie','code'=>'353','embassy'=>'0'],
            ['libelle'=>'Islande','alpha'=>'is','code'=>'354','embassy'=>'0'],
            ['libelle'=>'Israël','alpha'=>'il','code'=>'972','embassy'=>'0'],
            ['libelle'=>'Italie','alpha'=>'it','code'=>'39','embassy'=>'0'],
            ['libelle'=>'Japon','alpha'=>'jp','code'=>'81','embassy'=>'0'],
            ['libelle'=>'Jordanie','alpha'=>'jo','code'=>'962','embassy'=>'0'],
            ['libelle'=>'Kenya','alpha'=>'ke','code'=>'254','embassy'=>'0'],
            ['libelle'=>'Koweït','alpha'=>'kw','code'=>'965','embassy'=>'0'],
            ['libelle'=>'Laos','alpha'=>'la','code'=>'856','embassy'=>'0'],
            ['libelle'=>'Lettonie','alpha'=>'lv','code'=>'371','embassy'=>'0'],
            ['libelle'=>'Liban','alpha'=>'lb','code'=>'961','embassy'=>'0'],
            ['libelle'=>'Libye','alpha'=>'ly','code'=>'218','embassy'=>'0'],
            ['libelle'=>'Lituanie','alpha'=>'lt','code'=>'370','embassy'=>'0'],
            ['libelle'=>'Luxembourg','alpha'=>'lu','code'=>'352','embassy'=>'0'],
            ['libelle'=>'Madagascar','alpha'=>'mg','code'=>'261','embassy'=>'0'],
            ['libelle'=>'Malaisie','alpha'=>'my','code'=>'60','embassy'=>'0'],
            ['libelle'=>'Mali','alpha'=>'ml','code'=>'223','embassy'=>'0'],
            ['libelle'=>'Maroc','alpha'=>'ma','code'=>'212','embassy'=>'0'],
            ['libelle'=>'Mexique','alpha'=>'mx','code'=>'52','embassy'=>'0'],
            ['libelle'=>'Monaco','alpha'=>'mc','code'=>'377','embassy'=>'0'],
            ['libelle'=>'Mongolie','alpha'=>'mn','code'=>'976','embassy'=>'0'],
            ['libelle'=>'Mozambique','alpha'=>'mz','code'=>'258','embassy'=>'0'],
            ['libelle'=>'Namibie','alpha'=>'na','code'=>'264','embassy'=>'0'],
            ['libelle'=>'Népal','alpha'=>'np','code'=>'977','embassy'=>'0'],
            ['libelle'=>'Niger','alpha'=>'ne','code'=>'227','embassy'=>'0'],
            ['libelle'=>'Nigeria','alpha'=>'ng','code'=>'234','embassy'=>'0'],
            ['libelle'=>'Norvège','alpha'=>'no','code'=>'47','embassy'=>'0'],
            ['libelle'=>'Nouvelle-Zélande','alpha'=>'nz','code'=>'64','embassy'=>'0'],
            ['libelle'=>'Ouganda','alpha'=>'ug','code'=>'256','embassy'=>'0'],
            ['libelle'=>'Ouzbékistan','alpha'=>'uz','code'=>'998','embassy'=>'0'],
            ['libelle'=>'Pakistan','alpha'=>'pk','code'=>'92','embassy'=>'0'],
            ['libelle'=>'Panama','alpha'=>'pa','code'=>'507','embassy'=>'0'],
            ['libelle'=>'Paraguay','alpha'=>'py','code'=>'595','embassy'=>'0'],
            ['libelle'=>'Pays-Bas','alpha'=>'nl','code'=>'31','embassy'=>'0'],
            ['libelle'=>'Pérou','alpha'=>'pe','code'=>'51','embassy'=>'0'],
            ['libelle'=>'Philippines','alpha'=>'ph','code'=>'63','embassy'=>'0'],
            ['libelle'=>'Pologne','alpha'=>'pl','code'=>'48','embassy'=>'0'],
            ['libelle'=>'Portugal','alpha'=>'pt','code'=>'351','embassy'=>'0'],
            ['libelle'=>'Qatar','alpha'=>'qa','code'=>'974','embassy'=>'0'],
            ['libelle'=>'République centrafricaine','alpha'=>'cf','code'=>'236','embassy'=>'0'],
            ['libelle'=>'République dominicaine','alpha'=>'do','code'=>'1','embassy'=>'0'],
            ['libelle'=>'Roumanie','alpha'=>'ro','code'=>'40','embassy'=>'0'],
            ['libelle'=>'Royaume-Uni','alpha'=>'gb','code'=>'44','embassy'=>'0'],
            ['libelle'=>'Russie','alpha'=>'ru','code'=>'7','embassy'=>'0'],
            ['libelle'=>'Rwanda','alpha'=>'rw','code'=>'250','embassy'=>'0'],
            ['libelle'=>'Sénégal','alpha'=>'sn','code'=>'221','embassy'=>'0'],
            ['libelle'=>'Serbie','alpha'=>'rs','code'=>'381','embassy'=>'0'],
            ['libelle'=>'Sierra Leone','alpha'=>'sl','code'=>'232','embassy'=>'0'],
            ['libelle'=>'Singapour','alpha'=>'sg','code'=>'65','embassy'=>'0'],
            ['libelle'=>'Slovaquie','alpha'=>'sk','code'=>'421','embassy'=>'0'],
            ['libelle'=>'Slovénie','alpha'=>'si','code'=>'386','embassy'=>'0'],
            ['libelle'=>'Somalie','alpha'=>'so','code'=>'252','embassy'=>'0'],
            ['libelle'=>'Soudan','alpha'=>'sd','code'=>'249','embassy'=>'0'],
            ['libelle'=>'Soudan du Sud','alpha'=>'ss','code'=>'211','embassy'=>'0'],
            ['libelle'=>'Sri Lanka','alpha'=>'lk','code'=>'94','embassy'=>'0'],
            ['libelle'=>'Suède','alpha'=>'se','code'=>'46','embassy'=>'0'],
            ['libelle'=>'Suisse','alpha'=>'ch','code'=>'41','embassy'=>'0'],
            ['libelle'=>'Syrie','alpha'=>'sy','code'=>'963','embassy'=>'0'],
            ['libelle'=>'Tanzanie','alpha'=>'tz','code'=>'255','embassy'=>'0'],
            ['libelle'=>'Tchad','alpha'=>'td','code'=>'235','embassy'=>'0'],
            ['libelle'=>'Thaïlande','alpha'=>'th','code'=>'66','embassy'=>'0'],
            ['libelle'=>'Tunisie','alpha'=>'tn','code'=>'216','embassy'=>'0'],
            ['libelle'=>'Turquie','alpha'=>'tr','code'=>'90','embassy'=>'0'],
            ['libelle'=>'Ukraine','alpha'=>'ua','code'=>'380','embassy'=>'0'],
            ['libelle'=>'Uruguay','alpha'=>'uy','code'=>'598','embassy'=>'0'],
            ['libelle'=>'Venezuela','alpha'=>'ve','code'=>'58','embassy'=>'0'],
            ['libelle'=>'Viêt Nam','alpha'=>'vn','code'=>'84','embassy'=>'0'],
            ['libelle'=>'Yémen','alpha'=>'ye','code'=>'967','embassy'=>'0'],
            ['libelle'=>'Zambie','alpha'=>'zm','code'=>'260','embassy'=>'0'],
            ['libelle'=>'Zimbabwe','alpha'=>'zw','code'=>'263','embassy'=>'0'],
        ]);
    }
}