<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        Country::truncate();

        Country::insert([
            ['libelle'=>'Afghanistan','alpha'=>'af','code'=>'93','embassy'=>'0'],
            ['libelle'=>'Åland Islands','alpha'=>'ax','code'=>'358','embassy'=>'0'],
            ['libelle'=>'Albanie','alpha'=>'al','code'=>'355','embassy'=>'0'],
            ['libelle'=>'Algérie','alpha'=>'dz','code'=>'213','embassy'=>'0'],
            ['libelle'=>'Samoa Américaines','alpha'=>'as','code'=>'685','embassy'=>'0'],
            ['libelle'=>'Andorre','alpha'=>'ad','code'=>'376','embassy'=>'0'],
            ['libelle'=>'Angola','alpha'=>'ao','code'=>'244','embassy'=>'0'],
            ['libelle'=>'Anguilla','alpha'=>'ai','code'=>'1264','embassy'=>'0'],
            ['libelle'=>'Antigua-et-Barbuda','alpha'=>'ag','code'=>'1268','embassy'=>'0'],
            ['libelle'=>'Argentine','alpha'=>'ar','code'=>'54','embassy'=>'0'],
            ['libelle'=>'Arménie','alpha'=>'am','code'=>'374','embassy'=>'0'],
            ['libelle'=>'Aruba','alpha'=>'aw','code'=>'297','embassy'=>'0'],
            ['libelle'=>'Ascension Island','alpha'=>'ac','code'=>'247','embassy'=>'0'],
            ['libelle'=>'Australie','alpha'=>'au','code'=>'61','embassy'=>'0'],
            ['libelle'=>'Autriche','alpha'=>'at','code'=>'43','embassy'=>'0'],
            ['libelle'=>'Azerbaïdjan','alpha'=>'az','code'=>'994','embassy'=>'0'],
            ['libelle'=>'Bahamas','alpha'=>'bs','code'=>'1242','embassy'=>'0'],
            ['libelle'=>'Bahreïn','alpha'=>'bh','code'=>'973','embassy'=>'0'],
            ['libelle'=>'Bangladesh','alpha'=>'bd','code'=>'880','embassy'=>'0'],
            ['libelle'=>'Barbade','alpha'=>'bb','code'=>'1246','embassy'=>'0'],
            ['libelle'=>'Biélorussie','alpha'=>'by','code'=>'375','embassy'=>'0'],
            ['libelle'=>'Belgique','alpha'=>'be','code'=>'32','embassy'=>'0'],
            ['libelle'=>'Belize','alpha'=>'bz','code'=>'501','embassy'=>'0'],
            ['libelle'=>'Bénin','alpha'=>'bj','code'=>'229','embassy'=>'0'],
            ['libelle'=>'Bermudes','alpha'=>'bm','code'=>'1441','embassy'=>'0'],
            ['libelle'=>'Bhoutan','alpha'=>'bt','code'=>'975','embassy'=>'0'],
            ['libelle'=>'Bolivie','alpha'=>'bo','code'=>'591','embassy'=>'0'],
            ['libelle'=>'Bosnie-Herzégovine','alpha'=>'ba','code'=>'387','embassy'=>'0'],
            ['libelle'=>'Botswana','alpha'=>'bw','code'=>'267','embassy'=>'0'],
            ['libelle'=>'Brésil','alpha'=>'br','code'=>'55','embassy'=>'0'],
            ['libelle'=>'Territoire Britannique de l’Océan Indien','alpha'=>'io','code'=>'246','embassy'=>'0'],
            ['libelle'=>'Vierges britanniques','alpha'=>'vg','code'=>'1284','embassy'=>'0'],
            ['libelle'=>'Brunei','alpha'=>'bn','code'=>'673','embassy'=>'0'],
            ['libelle'=>'Bulgarie','alpha'=>'bg','code'=>'359','embassy'=>'0'],
            ['libelle'=>'Burkina Faso','alpha'=>'bf','code'=>'226','embassy'=>'0'],
            ['libelle'=>'Burundi','alpha'=>'bi','code'=>'257','embassy'=>'0'],
            ['libelle'=>'Cambodge','alpha'=>'kh','code'=>'855','embassy'=>'0'],
            ['libelle'=>'Cameroun','alpha'=>'cm','code'=>'237','embassy'=>'0'],
            ['libelle'=>'Canada','alpha'=>'ca','code'=>'1204','embassy'=>'0'],
            ['libelle'=>'Cap Vert','alpha'=>'cv','code'=>'238','embassy'=>'0'],
            ['libelle'=>'Antilles Néerlandaises','alpha'=>'bq','code'=>'599','embassy'=>'0'],
            ['libelle'=>'Caïman','alpha'=>'ky','code'=>'1345','embassy'=>'0'],
            ['libelle'=>'Centrafrique','alpha'=>'cf','code'=>'236','embassy'=>'0'],
            ['libelle'=>'Tchad','alpha'=>'td','code'=>'235','embassy'=>'0'],
            ['libelle'=>'Chili','alpha'=>'cl','code'=>'56','embassy'=>'0'],
            ['libelle'=>'Chine','alpha'=>'cn','code'=>'86','embassy'=>'0'],
            ['libelle'=>'Christmas','alpha'=>'cx','code'=>'61','embassy'=>'0'],
            ['libelle'=>'Cocos','alpha'=>'cc','code'=>'891','embassy'=>'0'],
            ['libelle'=>'Colombie','alpha'=>'co','code'=>'57','embassy'=>'0'],
            ['libelle'=>'Comores','alpha'=>'km','code'=>'269','embassy'=>'0'],
            ['libelle'=>'Cook','alpha'=>'ck','code'=>'682','embassy'=>'0'],
            ['libelle'=>'Costa Rica','alpha'=>'cr','code'=>'506','embassy'=>'0'],
            ['libelle'=>'Côte d’Ivoire','alpha'=>'ci','code'=>'225','embassy'=>'1'],
            ['libelle'=>'Croatie','alpha'=>'hr','code'=>'385','embassy'=>'0'],
            ['libelle'=>'Cuba','alpha'=>'cu','code'=>'53','embassy'=>'0'],
            ['libelle'=>'Curaçao','alpha'=>'cw','code'=>'599','embassy'=>'0'],
            ['libelle'=>'Chypre','alpha'=>'cy','code'=>'357','embassy'=>'0'],
            ['libelle'=>'Tchèque','alpha'=>'cz','code'=>'420','embassy'=>'0'],
            ['libelle'=>'Danemark','alpha'=>'dk','code'=>'45','embassy'=>'0'],
            ['libelle'=>'Djibouti','alpha'=>'dj','code'=>'253','embassy'=>'0'],
            ['libelle'=>'Dominique','alpha'=>'dm','code'=>'1767','embassy'=>'0'],
            ['libelle'=>'Dominicaine','alpha'=>'do','code'=>'1809','embassy'=>'0'],
            ['libelle'=>'Equateur','alpha'=>'ec','code'=>'593','embassy'=>'0'],
            ['libelle'=>'Egypte','alpha'=>'eg','code'=>'20','embassy'=>'0'],
            ['libelle'=>'El Salvador','alpha'=>'sv','code'=>'503','embassy'=>'0'],
            ['libelle'=>'Guinée Equatoriale','alpha'=>'gq','code'=>'240','embassy'=>'0'],
            ['libelle'=>'Erythrée','alpha'=>'er','code'=>'291','embassy'=>'0'],
            ['libelle'=>'Espagne','alpha'=>'es','code'=>'34','embassy'=>'0'],
            ['libelle'=>'Estonie','alpha'=>'ee','code'=>'372','embassy'=>'0'],
            ['libelle'=>'Eswatini','alpha'=>'sz','code'=>'268','embassy'=>'0'],
            ['libelle'=>'Ethiopie','alpha'=>'et','code'=>'251','embassy'=>'0'],
            ['libelle'=>'Malouines','alpha'=>'fk','code'=>'500','embassy'=>'0'],
            ['libelle'=>'Féroé','alpha'=>'fo','code'=>'298','embassy'=>'0'],
            ['libelle'=>'Fiji','alpha'=>'fj','code'=>'679','embassy'=>'0'],
            ['libelle'=>'Finlande','alpha'=>'fi','code'=>'358','embassy'=>'0'],
            ['libelle'=>'France','alpha'=>'fr','code'=>'33','embassy'=>'0'],
            ['libelle'=>'Gabon','alpha'=>'ga','code'=>'241','embassy'=>'0'],
            ['libelle'=>'Gambie','alpha'=>'gm','code'=>'220','embassy'=>'0'],
            ['libelle'=>'Géorgie','alpha'=>'ge','code'=>'995','embassy'=>'0'],
            ['libelle'=>'Allemagne','alpha'=>'de','code'=>'49','embassy'=>'0'],
            ['libelle'=>'Ghana','alpha'=>'gh','code'=>'233','embassy'=>'0'],
            ['libelle'=>'Gibraltar','alpha'=>'gi','code'=>'350','embassy'=>'0'],
            ['libelle'=>'Grèce','alpha'=>'gr','code'=>'30','embassy'=>'0'],
            ['libelle'=>'Groenland','alpha'=>'gl','code'=>'299','embassy'=>'0'],
            ['libelle'=>'Grenade','alpha'=>'gd','code'=>'1473','embassy'=>'0'],
            ['libelle'=>'Guadeloupe','alpha'=>'gp','code'=>'590','embassy'=>'0'],
            ['libelle'=>'Guam','alpha'=>'gu','code'=>'1671','embassy'=>'0'],
            ['libelle'=>'Guatemala','alpha'=>'gt','code'=>'502','embassy'=>'0'],
            ['libelle'=>'Guernsey','alpha'=>'gg','code'=>'44','embassy'=>'0'],
            ['libelle'=>'Guinée','alpha'=>'gn','code'=>'224','embassy'=>'0'],
            ['libelle'=>'Guinea-Bissau','alpha'=>'gw','code'=>'245','embassy'=>'0'],
            ['libelle'=>'Guyana','alpha'=>'gy','code'=>'592','embassy'=>'0'],
            ['libelle'=>'Guyane française','alpha'=>'gf','code'=>'594','embassy'=>'0'],
            ['libelle'=>'Haïti','alpha'=>'ht','code'=>'509','embassy'=>'0'],
            ['libelle'=>'Honduras','alpha'=>'hn','code'=>'504','embassy'=>'0'],
            ['libelle'=>'Hong Kong','alpha'=>'hk','code'=>'852','embassy'=>'0'],
            ['libelle'=>'Hongrie','alpha'=>'hu','code'=>'36','embassy'=>'0'],
            ['libelle'=>'Islande','alpha'=>'is','code'=>'354','embassy'=>'0'],
            ['libelle'=>'Inde','alpha'=>'in','code'=>'91','embassy'=>'0'],
            ['libelle'=>'Indonésie','alpha'=>'id','code'=>'62','embassy'=>'0'],
            ['libelle'=>'Iran','alpha'=>'ir','code'=>'98','embassy'=>'0'],
            ['libelle'=>'Irak','alpha'=>'iq','code'=>'964','embassy'=>'0'],
            ['libelle'=>'Irlande','alpha'=>'ie','code'=>'353','embassy'=>'0'],
            ['libelle'=>'Isle of Man','alpha'=>'im','code'=>'44','embassy'=>'0'],
            ['libelle'=>'Israël','alpha'=>'il','code'=>'972','embassy'=>'0'],
            ['libelle'=>'Italie','alpha'=>'it','code'=>'39','embassy'=>'0'],
            ['libelle'=>'Jamaïque','alpha'=>'jm','code'=>'1876','embassy'=>'0'],
            ['libelle'=>'Japon','alpha'=>'jp','code'=>'81','embassy'=>'0'],
            ['libelle'=>'Jersey','alpha'=>'je','code'=>'44','embassy'=>'0'],
            ['libelle'=>'Jordanie','alpha'=>'jo','code'=>'962','embassy'=>'0'],
            ['libelle'=>'Kazakhstan','alpha'=>'kz','code'=>'7','embassy'=>'0'],
            ['libelle'=>'Kenya','alpha'=>'ke','code'=>'254','embassy'=>'0'],
            ['libelle'=>'Kiribati','alpha'=>'ki','code'=>'686','embassy'=>'0'],
            ['libelle'=>'Kosovo','alpha'=>'xk','code'=>'383','embassy'=>'0'],
            ['libelle'=>'Koweït','alpha'=>'kw','code'=>'965','embassy'=>'0'],
            ['libelle'=>'Kirghizistan','alpha'=>'kg','code'=>'996','embassy'=>'0'],
            ['libelle'=>'Réunion','alpha'=>'re','code'=>'262','embassy'=>'0'],
            ['libelle'=>'Laos','alpha'=>'la','code'=>'856','embassy'=>'0'],
            ['libelle'=>'Lettonie','alpha'=>'lv','code'=>'371','embassy'=>'0'],
            ['libelle'=>'Liban','alpha'=>'lb','code'=>'961','embassy'=>'0'],
            ['libelle'=>'Lesotho','alpha'=>'ls','code'=>'266','embassy'=>'0'],
            ['libelle'=>'Liberia','alpha'=>'lr','code'=>'231','embassy'=>'0'],
            ['libelle'=>'Libye','alpha'=>'ly','code'=>'218','embassy'=>'0'],
            ['libelle'=>'Liechtenstein','alpha'=>'li','code'=>'423','embassy'=>'0'],
            ['libelle'=>'Lituanie','alpha'=>'lt','code'=>'370','embassy'=>'0'],
            ['libelle'=>'Luxembourg','alpha'=>'lu','code'=>'352','embassy'=>'0'],
            ['libelle'=>'Macao','alpha'=>'mo','code'=>'853','embassy'=>'0'],
            ['libelle'=>'Macédoine','alpha'=>'mk','code'=>'389','embassy'=>'0'],
            ['libelle'=>'Madagascar','alpha'=>'mg','code'=>'261','embassy'=>'0'],
            ['libelle'=>'Malawi','alpha'=>'mw','code'=>'265','embassy'=>'0'],
            ['libelle'=>'Malaisie','alpha'=>'my','code'=>'60','embassy'=>'0'],
            ['libelle'=>'Maldives','alpha'=>'mv','code'=>'960','embassy'=>'0'],
            ['libelle'=>'Mali','alpha'=>'ml','code'=>'223','embassy'=>'0'],
            ['libelle'=>'Malte','alpha'=>'mt','code'=>'356','embassy'=>'0'],
            ['libelle'=>'Marshall','alpha'=>'mh','code'=>'692','embassy'=>'0'],
            ['libelle'=>'Martinique','alpha'=>'mq','code'=>'596','embassy'=>'0'],
            ['libelle'=>'Mauritanie','alpha'=>'mr','code'=>'222','embassy'=>'0'],
            ['libelle'=>'Ile Maurice','alpha'=>'mu','code'=>'230','embassy'=>'0'],
            ['libelle'=>'Mayotte','alpha'=>'yt','code'=>'262','embassy'=>'0'],
            ['libelle'=>'Mexique','alpha'=>'mx','code'=>'52','embassy'=>'0'],
            ['libelle'=>'Micronésie','alpha'=>'fm','code'=>'691','embassy'=>'0'],
            ['libelle'=>'Moldavie','alpha'=>'md','code'=>'373','embassy'=>'0'],
            ['libelle'=>'Monaco','alpha'=>'mc','code'=>'377','embassy'=>'0'],
            ['libelle'=>'Mongolie','alpha'=>'mn','code'=>'976','embassy'=>'0'],
            ['libelle'=>'Monténégro','alpha'=>'me','code'=>'382','embassy'=>'0'],
            ['libelle'=>'Montserrat','alpha'=>'ms','code'=>'1664','embassy'=>'0'],
            ['libelle'=>'Maroc','alpha'=>'ma','code'=>'212','embassy'=>'0'],
            ['libelle'=>'Mozambique','alpha'=>'mz','code'=>'258','embassy'=>'0'],
            ['libelle'=>'Myanmar','alpha'=>'mm','code'=>'95','embassy'=>'0'],
            ['libelle'=>'Namibie','alpha'=>'na','code'=>'264','embassy'=>'0'],
            ['libelle'=>'Nauru','alpha'=>'nr','code'=>'674','embassy'=>'0'],
            ['libelle'=>'Népal','alpha'=>'np','code'=>'977','embassy'=>'0'],
            ['libelle'=>'country-Bas','alpha'=>'nl','code'=>'31','embassy'=>'0'],
            ['libelle'=>'Nouvelle-Calédonie','alpha'=>'nc','code'=>'687','embassy'=>'0'],
            ['libelle'=>'Nouvelle-Zélande','alpha'=>'nz','code'=>'64','embassy'=>'0'],
            ['libelle'=>'Nicaragua','alpha'=>'ni','code'=>'505','embassy'=>'0'],
            ['libelle'=>'Niger','alpha'=>'ne','code'=>'227','embassy'=>'0'],
            ['libelle'=>'Nigeria','alpha'=>'ng','code'=>'234','embassy'=>'0'],
            ['libelle'=>'Niue','alpha'=>'nu','code'=>'683','embassy'=>'0'],
            ['libelle'=>'Norfolk','alpha'=>'nf','code'=>'672','embassy'=>'0'],
            ['libelle'=>'Corée du Nord','alpha'=>'kp','code'=>'850','embassy'=>'0'],
            ['libelle'=>'Mariannes du Nord','alpha'=>'mp','code'=>'1670','embassy'=>'0'],
            ['libelle'=>'Norvège','alpha'=>'no','code'=>'47','embassy'=>'0'],
            ['libelle'=>'Oman','alpha'=>'om','code'=>'968','embassy'=>'0'],
            ['libelle'=>'Pakistan','alpha'=>'pk','code'=>'92','embassy'=>'0'],
            ['libelle'=>'Palaos','alpha'=>'pw','code'=>'680','embassy'=>'0'],
            ['libelle'=>'Palestine','alpha'=>'ps','code'=>'970','embassy'=>'0'],
            ['libelle'=>'Panamá','alpha'=>'pa','code'=>'507','embassy'=>'0'],
            ['libelle'=>'Papouasie-Nouvelle-Guinée','alpha'=>'pg','code'=>'675','embassy'=>'0'],
            ['libelle'=>'Paraguay','alpha'=>'py','code'=>'595','embassy'=>'0'],
            ['libelle'=>'Pérou','alpha'=>'pe','code'=>'51','embassy'=>'0'],
            ['libelle'=>'Philippines','alpha'=>'ph','code'=>'63','embassy'=>'0'],
            ['libelle'=>'Pologne','alpha'=>'pl','code'=>'48','embassy'=>'0'],
            ['libelle'=>'Polynésie française','alpha'=>'pf','code'=>'689','embassy'=>'0'],
            ['libelle'=>'Portugal','alpha'=>'pt','code'=>'351','embassy'=>'0'],
            ['libelle'=>'Porto Rico','alpha'=>'pr','code'=>'1787','embassy'=>'0'],
            ['libelle'=>'Qatar','alpha'=>'qa','code'=>'974','embassy'=>'0'],
            ['libelle'=>'Congo Kinshasa','alpha'=>'cd','code'=>'243','embassy'=>'0'],
            ['libelle'=>'Congo Brazzaville','alpha'=>'cg','code'=>'242','embassy'=>'0'],
            ['libelle'=>'Roumanie','alpha'=>'ro','code'=>'40','embassy'=>'0'],
            ['libelle'=>'Russie','alpha'=>'ru','code'=>'7','embassy'=>'0'],
            ['libelle'=>'Rwanda','alpha'=>'rw','code'=>'250','embassy'=>'0'],
            ['libelle'=>'Saint-Barthélemy','alpha'=>'bl','code'=>'590','embassy'=>'0'],
            ['libelle'=>'Saint-Helena','alpha'=>'sh','code'=>'290','embassy'=>'0'],
            ['libelle'=>'Saint-Christophe-et-Niévès','alpha'=>'kn','code'=>'1869','embassy'=>'0'],
            ['libelle'=>'Sainte-Lucie','alpha'=>'lc','code'=>'1758','embassy'=>'0'],
            ['libelle'=>'Saint-Martin','alpha'=>'mf','code'=>'590','embassy'=>'0'],
            ['libelle'=>'Saint-Pierre-et-Miquelon','alpha'=>'pm','code'=>'508','embassy'=>'0'],
            ['libelle'=>'Saint-Vincent-et-les Grenadines','alpha'=>'vc','code'=>'1784','embassy'=>'0'],
            ['libelle'=>'San Marino','alpha'=>'sm','code'=>'378','embassy'=>'0'],
            ['libelle'=>'Sao Tomé-et-Principe','alpha'=>'st','code'=>'239','embassy'=>'0'],
            ['libelle'=>'Arabie saoudite','alpha'=>'sa','code'=>'966','embassy'=>'0'],
            ['libelle'=>'Sénégal','alpha'=>'sn','code'=>'221','embassy'=>'0'],
            ['libelle'=>'Serbie','alpha'=>'rs','code'=>'381','embassy'=>'0'],
            ['libelle'=>'Seychelles','alpha'=>'sc','code'=>'248','embassy'=>'0'],
            ['libelle'=>'Sierra Leone','alpha'=>'sl','code'=>'232','embassy'=>'0'],
            ['libelle'=>'Singapour','alpha'=>'sg','code'=>'65','embassy'=>'0'],
            ['libelle'=>'Sint Maarten','alpha'=>'sx','code'=>'1721','embassy'=>'0'],
            ['libelle'=>'Slovaquie','alpha'=>'sk','code'=>'421','embassy'=>'0'],
            ['libelle'=>'Slovénie','alpha'=>'si','code'=>'386','embassy'=>'0'],
            ['libelle'=>'Solomon','alpha'=>'sb','code'=>'677','embassy'=>'0'],
            ['libelle'=>'Somalie','alpha'=>'so','code'=>'252','embassy'=>'0'],
            ['libelle'=>'Afrique du Sud','alpha'=>'za','code'=>'27','embassy'=>'0'],
            ['libelle'=>'Corée du Sud','alpha'=>'kr','code'=>'82','embassy'=>'0'],
            ['libelle'=>'Soudan du Sud','alpha'=>'ss','code'=>'211','embassy'=>'0'],
            ['libelle'=>'Sri Lanka','alpha'=>'lk','code'=>'94','embassy'=>'0'],
            ['libelle'=>'Soudan','alpha'=>'sd','code'=>'249','embassy'=>'0'],
            ['libelle'=>'Suriname','alpha'=>'sr','code'=>'597','embassy'=>'0'],
            ['libelle'=>'Svalbard et Jan Mayen','alpha'=>'sj','code'=>'47','embassy'=>'0'],
            ['libelle'=>'Sweden','alpha'=>'se','code'=>'46','embassy'=>'0'],
            ['libelle'=>'Suisse','alpha'=>'ch','code'=>'41','embassy'=>'0'],
            ['libelle'=>'Syrie','alpha'=>'sy','code'=>'963','embassy'=>'0'],
            ['libelle'=>'Taïwan','alpha'=>'tw','code'=>'886','embassy'=>'0'],
            ['libelle'=>'Tadjikistan','alpha'=>'tj','code'=>'992','embassy'=>'0'],
            ['libelle'=>'Tanzanie','alpha'=>'tz','code'=>'255','embassy'=>'0'],
            ['libelle'=>'Thaïlande','alpha'=>'th','code'=>'66','embassy'=>'0'],
            ['libelle'=>'Timor Oriental','alpha'=>'tl','code'=>'670','embassy'=>'0'],
            ['libelle'=>'Togo','alpha'=>'tg','code'=>'228','embassy'=>'0'],
            ['libelle'=>'Tokelau','alpha'=>'tk','code'=>'690','embassy'=>'0'],
            ['libelle'=>'Tonga','alpha'=>'to','code'=>'676','embassy'=>'0'],
            ['libelle'=>'Trinité-et-Tobago','alpha'=>'tt','code'=>'1868','embassy'=>'0'],
            ['libelle'=>'Tunisie','alpha'=>'tn','code'=>'216','embassy'=>'0'],
            ['libelle'=>'Turquie','alpha'=>'tr','code'=>'90','embassy'=>'0'],
            ['libelle'=>'Turkménistan','alpha'=>'tm','code'=>'993','embassy'=>'0'],
            ['libelle'=>'Turques et Caïques','alpha'=>'tc','code'=>'1649','embassy'=>'0'],
            ['libelle'=>'Tuvalu','alpha'=>'tv','code'=>'688','embassy'=>'0'],
            ['libelle'=>'Vierges des Etats-Unis','alpha'=>'vi','code'=>'1340','embassy'=>'0'],
            ['libelle'=>'Ouganda','alpha'=>'ug','code'=>'256','embassy'=>'0'],
            ['libelle'=>'Ukraine','alpha'=>'ua','code'=>'380','embassy'=>'0'],
            ['libelle'=>'Emirats Arabes Unis','alpha'=>'ae','code'=>'971','embassy'=>'0'],
            ['libelle'=>'Royaume-Uni','alpha'=>'gb','code'=>'44','embassy'=>'0'],
            ['libelle'=>'Etats-Unis','alpha'=>'us','code'=>'1','embassy'=>'0'],
            ['libelle'=>'Uruguay','alpha'=>'uy','code'=>'598','embassy'=>'0'],
            ['libelle'=>'Ouzbékistan','alpha'=>'uz','code'=>'998','embassy'=>'0'],
            ['libelle'=>'Vanuatu','alpha'=>'vu','code'=>'678','embassy'=>'0'],
            ['libelle'=>'Vatican','alpha'=>'va','code'=>'39','embassy'=>'0'],
            ['libelle'=>'Venezuela','alpha'=>'ve','code'=>'58','embassy'=>'0'],
            ['libelle'=>'Viêt Nam','alpha'=>'vn','code'=>'84','embassy'=>'0'],
            ['libelle'=>'Wallis-et-Futuna','alpha'=>'wf','code'=>'681','embassy'=>'0'],
            ['libelle'=>'Sahara Occidental','alpha'=>'eh','code'=>'212','embassy'=>'0'],
            ['libelle'=>'Yémen','alpha'=>'ye','code'=>'967','embassy'=>'0'],
            ['libelle'=>'Zambie','alpha'=>'zm','code'=>'260','embassy'=>'0'],
            ['libelle'=>'Zimbabwe','alpha'=>'zw','code'=>'263','embassy'=>'0'],
        ]);
    }
}