<?php

namespace Database\Seeders;

use App\Models\Nationality;
use Illuminate\Database\Seeder;

class NationalitySeeder extends Seeder
{
    public function run(): void
    {
        Nationality::truncate();

        Nationality::insert([
            ['libelle' => 'Afghane'],
            ['libelle' => 'Albanaise'],
            ['libelle' => 'Algérienne'],
            ['libelle' => 'Allemande'],
            ['libelle' => 'Américaine'],
            ['libelle' => 'Angolaise'],
            ['libelle' => 'Argentine'],
            ['libelle' => 'Arménienne'],
            ['libelle' => 'Australienne'],
            ['libelle' => 'Autrichienne'],
            ['libelle' => 'Belge'],
            ['libelle' => 'Béninoise'],
            ['libelle' => 'Burkinabè'],
            ['libelle' => 'Burundaise'],
            ['libelle' => 'Camerounaise'],
            ['libelle' => 'Canadienne'],
            ['libelle' => 'Centrafricaine'],
            ['libelle' => 'Chilienne'],
            ['libelle' => 'Chinoise'],
            ['libelle' => 'Colombienne'],
            ['libelle' => 'Congolaise'],
            ['libelle' => 'Croate'],
            ['libelle' => 'Cubaine'],
            ['libelle' => 'Danoise'],
            ['libelle' => 'Djiboutienne'],
            ['libelle' => 'Dominicaine'],
            ['libelle' => 'Egyptienne'],
            ['libelle' => 'Emiratie'],
            ['libelle' => 'Espagnole'],
            ['libelle' => 'Estonienne'],
            ['libelle' => 'Ethiopienne'],
            ['libelle' => 'Finlandaise'],
            ['libelle' => 'Française'],
            ['libelle' => 'Gabonaise'],
            ['libelle' => 'Gambienne'],
            ['libelle' => 'Ghanéenne'],
            ['libelle' => 'Grecque'],
            ['libelle' => 'Guinéenne'],
            ['libelle' => 'Haïtienne'],
            ['libelle' => 'Hollandaise'],
            ['libelle' => 'Hongroise'],
            ['libelle' => 'Indienne'],
            ['libelle' => 'Indonésienne'],
            ['libelle' => 'Irakienne'],
            ['libelle' => 'Iranienne'],
            ['libelle' => 'Irlandaise'],
            ['libelle' => 'Israélienne'],
            ['libelle' => 'Italienne'],
            ['libelle' => 'Ivoirienne'],
            ['libelle' => 'Japonaise'],
            ['libelle' => 'Jordanienne'],
            ['libelle' => 'Kényane'],
            ['libelle' => 'Koweïtienne'],
            ['libelle' => 'Libanaise'],
            ['libelle' => 'Libyenne'],
            ['libelle' => 'Malaisienne'],
            ['libelle' => 'Malienne'],
            ['libelle' => 'Marocaine'],
            ['libelle' => 'Mauritanienne'],
            ['libelle' => 'Mexicaine'],
            ['libelle' => 'Monégasque'],
            ['libelle' => 'Nigérienne'],
            ['libelle' => 'Nigériane'],
            ['libelle' => 'Norvégienne'],
            ['libelle' => 'Ougandaise'],
            ['libelle' => 'Pakistanaise'],
            ['libelle' => 'Péruvienne'],
            ['libelle' => 'Polonaise'],
            ['libelle' => 'Portugaise'],
            ['libelle' => 'Qatarie'],
            ['libelle' => 'Roumaine'],
            ['libelle' => 'Russe'],
            ['libelle' => 'Rwandaise'],
            ['libelle' => 'Sénégalaise'],
            ['libelle' => 'Serbe'],
            ['libelle' => 'Sierra Léonaise'],
            ['libelle' => 'Singapourienne'],
            ['libelle' => 'Slovaque'],
            ['libelle' => 'Somalienne'],
            ['libelle' => 'Soudanaise'],
            ['libelle' => 'Suédoise'],
            ['libelle' => 'Suisse'],
            ['libelle' => 'Syrienne'],
            ['libelle' => 'Tanzanienne'],
            ['libelle' => 'Tchadienne'],
            ['libelle' => 'Thaïlandaise'],
            ['libelle' => 'Togolaise'],
            ['libelle' => 'Tunisienne'],
            ['libelle' => 'Turque'],
            ['libelle' => 'Ukrainienne'],
            ['libelle' => 'Uruguayenne'],
            ['libelle' => 'Vénézuélienne'],
            ['libelle' => 'Vietnamienne'],
            ['libelle' => 'Zambienne'],
            ['libelle' => 'Zimbabwéenne'],
        ]);
    }
}